### PR TITLE
Remove separate getters/setters for neighbouring tiles

### PR DESCRIPTION
**Pull request by atg-abhijay**
Currently, there are individual getters/setters for the North, South, East, West tiles. But there exist two methods already which are capable of handling the functionality of those individual getters/setters.
https://github.com/COMP361/f2018-group10/blob/a0f5b80bc84583f9bb8e4f60500749ecca61abab/FlashPoint/src/models/game_board/tile_model.py#L188-L196
https://github.com/COMP361/f2018-group10/blob/a0f5b80bc84583f9bb8e4f60500749ecca61abab/FlashPoint/src/models/game_board/tile_model.py#L185-L186

Refactor the code to use the two methods above instead. `get_tile_in_direction()` had to be tweaked a bit so that it's functionality would match that of the individual getters.

### CODE REVIEW

**Comment by hawschiat** [comment]
Are keys case-sensitive in Python? If it is then we need to implement a check for the cases of keys as well

**Comment by atg-abhijay** [comment]
Yes, keys are case-sensitive in Python. But the way the new code works:
https://github.com/COMP361/f2018-group10/blob/f1c43715b6785387f9af9008506b84209ec77de7/FlashPoint/src/models/game_board/tile_model.py#L128-L137

The second parameter to the `get()` method specifies the value to return if the key cannot be found. It would return `None` in that case and that would be immediately caught in the `if` condition and an exception would be thrown, so it's all good :)

**Comment by hawschiat** [comment]
If it were up to me, I'd do some conversion myself to make it handle the wrong cases, but that works too

**Comment by atg-abhijay** [comment]
Well, we adopted a standard of using the directions `North, South, East, West` and it's always weird and tricky to check for all sorts of arguments that could be provided - e.g. `n`, `north`, `N` etc.

I've gone through the usage of that method and checked the arguments that are passed to it each time and it's done in a fairly controlled manner so I think it's fine.

**Pull request merged**
